# This workflow fires off of pushes to develop branch. If the head commit message contains '[ci skip]', the whole workflow will be skipped.
#
# Secrets used:

name: Build and Deploy API

on:
  push:
    branches: [never] # change back to trigger branches when ready for deploy
    paths:
      - 'Template.API/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  environmentSuffix: ${{ endsWith(github.ref_name, 'develop') && 'd' || endsWith(github.ref_name, 'master') && 'd' || 't' }} # when ready for p, change d back to p for master (or whatever prod branch)

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest
    environment: ${{ endsWith(github.ref_name, 'develop') && 'Development' || endsWith(github.ref_name, 'master') && 'Production' || 'Test' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Dotnet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Use cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Test
        run: dotnet test

      - name: Build API
        run: |
          cd ./Template.API
          dotnet publish -c=Release -o dist

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Template-api-b${{ github.run_number }}
          path: ./Template.API/dist

  deploy-azure:
    name: Deploy to Azure App service
    runs-on: ubuntu-latest
    environment: ${{ endsWith(github.ref_name, 'develop') && 'Development' || endsWith(github.ref_name, 'master') && 'Production' || 'Test' }}
    needs:
      - build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App ${{ format('Template-api-uw-wa-{0}', env.environmentSuffix) }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ format('Template-api-uw-wa-{0}', env.environmentSuffix) }}
          slot-name: 'production'
          package: Template-api-b${{ github.run_number }}
